[package]
name = "hledger-import"
version = "0.1.0"
edition = "2021"

[features]
erste-json = []
all = ["erste-json"]

[dependencies]
bigdecimal = "0.4.4"
chrono = {version = "0.4.38", features = ["serde"]}
clap = { version = "4.5.7", features = ["derive"] }
homedir = "0.2.1"
num-format = {version = "0.4.4", features = ["with-num-bigint"]}
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
toml = "0.8.14"
