name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Feature tests "Revolut"
      run: cargo test --no-default-features --features "revolut" --verbose
    - name: Feature tests "Erste"
      run: cargo test --no-default-features --features "erste" --verbose
    - name: Feature tests "Cardcomplete"
      run: cargo test --no-default-features --features "cardcomplete" --verbose
    - name: Feature tests "Flatex"
      run: cargo test --no-default-features --features "flatex" --verbose
