name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install latest stable Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Update Rust to latest
      run: rustup update stable
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Feature tests "Revolut"
      run: cargo test --no-default-features --features "revolut" --verbose
    - name: Feature tests "Erste"
      run: cargo test --no-default-features --features "erste" --verbose
    - name: Feature tests "Cardcomplete"
      run: cargo test --no-default-features --features "cardcomplete" --verbose
    - name: Feature tests "Flatex"
      run: cargo test --no-default-features --features "flatex" --verbose
